### PR TITLE
GitHub Action to test Python code

### PR DESCRIPTION
**Pull request by cclauss**
Output: https://github.com/cclauss/nfelib/actions

Travis CI seems to be no longer active...

### CODE REVIEW

**Comment by rvalyi** [comment]
Hello @cclauss. I'm very much OK to move to Github actions. As for linting the Python generated code, I prefer to stay away from it for now. Indeed it will introduce artificial diff with the code generated next time if the generator has some changes. And spotting real changes easily over formatting is really what matters here (changes usually happen because of schemas updates or because of changes in generateDS).

Also while one can read/debug/hack the nfelib generated code, this is usually not some code you will spend time into. It's more of a black box that is tested to get the job done. Instead as for us who work with the Odoo ERP, we have an equivalent NFe Odoo abstract model:
https://github.com/akretion/l10n-brazil/blob/12.0-l10n_br_nfe_spec-update/l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
This is the nice NFe code we eventually read when we need. Then we automatically convert this abstract model back and forth to nfelib and use nfelib pretty much as a black box unless we suspect a bug.

It is generated with this generateDS plugin https://github.com/akretion/generateds-odoo
Similar plugins can target other frameworks/ERPs...

I'll comment more about code formatting in a few weeks. Meanwhile if you do a PR focusing on moving to testing with Github Actions I'm OK to merge it. What do you think?

**Comment by cclauss** [comment]
Are there particular directories that contain generated code because we could `exclude` them from analysis.

**Comment by rvalyi** [comment]
So in fact most of the lib is generated code... We could almost generate it on the fly even, but having it in a Github repo is a safe way to track evolutions (due to new schema versions or changes in the generator).

So the `nfelib`directory is all generated code. And instead `src` and `tests` is hand written code. `src` is a collection of snall overrides where we need them and as allowed by GenerateDS. We could format/analysis src and tests, but IMHO the benefice is very little for so little code.

**Comment by cclauss** [comment]
OK...  I have slimmed this down to just bandit (security), the most essential flake8 tests, and pytest.  If these test break, we should know about it.

**Pull request closed without merging**
